server:
  port: 8000
spring:
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
   application:
    name: provider
eureka:
  client:
    register-with-eureka: true  #是否将自己注册到Eureka Server，
    fetch-registry: true
    service-url:
     defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka
  instance:
    prefer-ip-address: false   #表示将微服务自己的ip注册到注册中心(Eureka Server)上，不配置表示将hostname注册到上面去
    metadata-map:
      name: 赵瑞文
      age: 25
      university: 山西大学
security:
  basic:
    enabled: true  #启用springsecurity的配置项
  user:
    name: zrw
    password: 8000
    role:
    - Admin